### ISSUE TITLE
Encoder(s) setup clarification

### ISSUE THREAD

**Issue by 2ynn** [zzeneg/pica40#1]
Great design! thanks for sharing.

If I understand correctly, for the wired configuration (XIAO RP2040, left as master) I can only get a single encoder.

According to your [QMK info.json](https://github.com/qmk/qmk_firmware/blob/f56580404d44af8a0e8b7205618c084a9acb3772/keyboards/pica40/rev2/info.json#L43), both ENC_A and ENC_B pads are connected to GP27.

I assume then that I should close jumpers JP6 (passing data to left side), JP3 (receiving data from right side) and JP1 (joining both encoder pins). Is that correct?

In this configuration, I am confused as to how you are able to detect the direction of the rotation. Is there a QMK configuration I am missing? 

Thanks!

**Comment by zzeneg** [comment]
Hi! Thanks for the interest!
For wired version encoder logic is a bit tricky and unique, as there is only 1 free pin on each MCU.
You are correct that you need to close those jumpers, and by doing so you are connecting encoder's B pin to the MCU on another half (using 4th wire in TRRS/USB-C interconnection).
There is [custom code](https://github.com/qmk/qmk_firmware/blob/f56580404d44af8a0e8b7205618c084a9acb3772/keyboards/pica40/rev2/rev2.c#L54) for encoder logic which looks intimidating but it only changes reading second pin's state from split transport transaction instead of a physical pin.
ENC_B from configuration is not used and added only because QMK validates it.

**Comment by 2ynn** [comment]
Thanks for your response, this is brilliant! 

I think I got the jumpers wrong then. If i want the encoder on the left side (master),  I should leave JP1 open (to not short the encoder) but close JP4 to connect `ENCB ==ttrs== ENCB_r` to `ENCA_r` , which is then read by the `encoders_pad_b_[0] = GP27` on the right side (slave) and then processed by `encoder_sync_slave_handler()`

So if I understand well setting `ENCODERS_PAD_B` to [GP27] actually matters in your custom code, not just for QMK, since you are always reading ENC_A/ENC_A_r (in the Wired configuration at least).

**Comment by zzeneg** [comment]
You should bridge the "no enc" jumper on a half without encoder, if it makes more sense :)
Actually I use A/B in code interchangeably, since it will always be the same single pin on any side. I simplified it a bit in my dev branch - https://github.com/zzeneg/qmk_firmware/blob/feature/pica40/keyboards/pica40/rev2/rev2.c, just didn't open PR to main repo yet.
